// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// MockAPIServiceInterface is an autogenerated mock type for the APIServiceInterface type
type MockAPIServiceInterface struct {
	mock.Mock
}

// GetTestMessage provides a mock function with given fields:
func (_m *MockAPIServiceInterface) GetTestMessage() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTestMessage")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// NewMockAPIServiceInterface creates a new instance of MockAPIServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mock's expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIServiceInterface {
	mock := &MockAPIServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}