run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
    - goconst
    - misspell
    - lll
    - gocyclo
    - dupl
    - unparam
    - nakedret
    - prealloc
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  lll:
    line-length: 120
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  nakedret:
    max-func-lines: 30
  
  gosec:
    excludes:
      - G204  # Subprocess launched with variable
    
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
    - path: internal/model
      linters:
        - lll
  
  max-issues-per-linter: 0
  max-same-issues: 0