// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthHandlerInterface is an autogenerated mock type for the HealthHandlerInterface type
type MockHealthHandlerInterface struct {
	mock.Mock
}

type MockHealthHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthHandlerInterface) EXPECT() *MockHealthHandlerInterface_Expecter {
	return &MockHealthHandlerInterface_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: c
func (_m *MockHealthHandlerInterface) Check(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthHandlerInterface_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockHealthHandlerInterface_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockHealthHandlerInterface_Expecter) Check(c interface{}) *MockHealthHandlerInterface_Check_Call {
	return &MockHealthHandlerInterface_Check_Call{Call: _e.mock.On("Check", c)}
}

func (_c *MockHealthHandlerInterface_Check_Call) Run(run func(c echo.Context)) *MockHealthHandlerInterface_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockHealthHandlerInterface_Check_Call) Return(_a0 error) *MockHealthHandlerInterface_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthHandlerInterface_Check_Call) RunAndReturn(run func(echo.Context) error) *MockHealthHandlerInterface_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthHandlerInterface creates a new instance of MockHealthHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthHandlerInterface {
	mock := &MockHealthHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
