// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockUserHandlerInterface is an autogenerated mock type for the UserHandlerInterface type
type MockUserHandlerInterface struct {
	mock.Mock
}

type MockUserHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserHandlerInterface) EXPECT() *MockUserHandlerInterface_Expecter {
	return &MockUserHandlerInterface_Expecter{mock: &_m.Mock}
}

// Me provides a mock function with given fields: c
func (_m *MockUserHandlerInterface) Me(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserHandlerInterface_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockUserHandlerInterface_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockUserHandlerInterface_Expecter) Me(c interface{}) *MockUserHandlerInterface_Me_Call {
	return &MockUserHandlerInterface_Me_Call{Call: _e.mock.On("Me", c)}
}

func (_c *MockUserHandlerInterface_Me_Call) Run(run func(c echo.Context)) *MockUserHandlerInterface_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockUserHandlerInterface_Me_Call) Return(_a0 error) *MockUserHandlerInterface_Me_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserHandlerInterface_Me_Call) RunAndReturn(run func(echo.Context) error) *MockUserHandlerInterface_Me_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserHandlerInterface creates a new instance of MockUserHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserHandlerInterface {
	mock := &MockUserHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
